// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xskblpmoahgdbcocmukp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhza2JscG1vYWhnZGJjb2NtdWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjc1NDEsImV4cCI6MjA2MDcwMzU0MX0.lzteh5kafGHylZ3ZWo04AZExneWYwHcmbQK3fl8QCmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);